version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: task
    container_name: flask_app
    ports:
      - 8080:8080
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: code/server.py
      REDIS_DB: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
    user: 1001:1001
    entrypoint: "python"
    command: ["-m", "flask", "run", "-h", "0.0.0.0", "-p", "8080"]
    volumes:
      - './app:/home/peon/code:ro' # enable hot reloading during development.
    depends_on:
      - cache

  cache:
    image: redis:7
    restart: always
    hostname: redis
    container_name: redis_db
    ports:
      - 6379:6379

  rcli:
    image: redis:7
    links:
      - cache
    volumes:
      - './sample:/home:ro'
    command: >
      sh -c 'redis-cli -h redis -p 6379 -n 1 < /home/import_keys.redis'
    depends_on:
      - cache
