apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  username: {{ .Values.redisUser | b64enc }}
  password: {{ .Values.redisPassword | b64enc }}
  host: {{ .Values.redisHost | b64enc }}
  port: {{ .Values.redisPort | toString | b64enc }}
  database: {{ .Values.redisDb | toString | b64enc }}
